config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  devise_for :users
  root 'home#index'
  get 'home/nosotros'

  post "/" => 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord
	belongs_to :user
	validates :ticker, presence: true
	validates :ticker, format: { without: /\s/ }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :stocks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @api = StockQuote::Stock.new(api_key: 'pk_9a3fffc17adf4052ac921fb0e57968bc')
    if params[:ticker] == ""
      @nada = "Ehh! Has olvidado entrar la búsqueda"
    elsif params[:ticker]
      begin
        @stock = StockQuote::Stock.quote( params[:ticker] )
      rescue => e
        @stock = nil
      end
      if @stock == nil
          @error = "Ehh! Ese símbolo no existe" 
      end
    end
  end
  def nosotros
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: %i[ show edit update destroy ]
  before_action :correct_user, only: %i[ edit update destroy ]
  before_action :authenticate_user!


  # GET /stocks or /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1 or /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks or /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: "Stock was successfully created." }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1 or /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: "Stock was successfully updated." }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1 or /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: "Stock was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @ticker = current_user.stocks.find_by(id: params[:id])
    redirect_to stocks_path, notice: "No autorizado a editar" if @ticker.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stock_params
      params.require(:stock).permit(:ticker, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/home/_flash.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= content_tag(:div, msg) %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/home/_navbar.html.erb
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <%= link_to "Stocking", root_path, class: "navbar-brand" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      
        <li class="nav-item">
          <%= link_to "Nosotros", home_nosotros_path, class: "nav-link" %>
        </li>

        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Editar Perfil", edit_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Mostrar Stocks", stocks_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Agregar Stock", new_stock_path, class: "nav-link" %>
          </li>
          
          <li class="nav-item">
            <%= link_to "Salir", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Iniciar", new_user_session_path, class: "nav-link" %>
          </li>
          
          <li class="nav-item">
            <%= link_to "Registrase", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
        
        
        
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Buscar" aria-label="Search">
        <button class="btn btn-outline-light" type="submit">Buscar</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Stocking</h1>
<%= form_tag root_path, :method => 'POST' do %>
	<%= text_field_tag "ticker", nil, placeholder: "Entre símbolo - ticker", size: 50 %>
	<%= submit_tag 'Buscar' %>
<% end %>

<% if @stock %>
	<%= @stock.company_name %><br/> 
	<%= @stock.latest_price %><br/> 
<% elsif @nada %>
	<%= @nada %>
<% end %>

<% if @error %>
	<%= @error %>
<% end %>

app/views/home/nosotros.html.erb
<h1>Página Nosotros</h1>
<p>Y esto también cambiará</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stocking</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "home/navbar" %>
    <br/>
    <div class="container">
      <%= render "home/flash" %> 
      <%= yield %>
    </div>
  </body>
</html>

app/views/stocks/_form.html.erb
<%= form_with(model: stock) do |form| %>
  <% if stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
        <% stock.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ticker %>
    <%= form.text_field :ticker %>
  </div>

  <div class="field">
    <%= form.number_field :user_id, value: current_user.id, type: :hidden %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<table class="table table-bordered table-hover table-striped">
  <thead class="table-dark">
    <tr>
      <th>Empresa</th>
      <th>Ticker</th>
      <th>Precio Actual</th>
      <th>Capital</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
      <% if stock.user_id == current_user.id %>
        <% begin %>
          <% @ticker = StockQuote::Stock.quote(stock.ticker) %>
        <% rescue => e %>
          <% @ticker = nil %>
        <% end %>
        <% if @ticker == nil %>
          <tr>
            <td><%= link_to "Error", stock %></td>
            <td><%= stock.ticker %></td>
            <td>n/a</td>
            <td>n/a</td>
            <td><center><%= link_to 'Editar', edit_stock_path(stock) %></center></td>
            <td><center><%= link_to 'Borrar', stock, method: :delete, data: { confirm: 'Estás seguro?' } %></center></td>
          </tr>
        <% else %>
          <tr>
          <td><%= link_to @ticker.company_name, stock %></td>
          <td><%= @ticker.symbol %></td>
          <td>$<%= number_with_precision(@ticker.latest_price, :precision =>2, :delimiter => ',') %></td>
          <td>$<%= number_with_precision(@ticker.market_cap, :precision =>0, :delimiter => ',') %></td>
          <td><center><%= link_to 'Editar', edit_stock_path(stock) %></center></td>
          <td><center><%= link_to 'Borrar', stock, method: :delete, data: { confirm: 'Estás seguro?' } %></center></td>
        </tr>
      
          <% end %>

        <% end %>

      <% end %>

        
      
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Stock', new_stock_path %>

app/views/stocks/new.html.erb
<h1>New Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<% begin %>
  <% @ticker = StockQuote::Stock.quote(@stock.ticker) %>
<% rescue => e %>
  <% @ticker = nil %>
<% end %>

<% if @ticker == nil %>
        El símbolo <%= @stock.ticker %> no existe </td>
<% else %>

<div class="card mb-3 text-white bg-primary" >
  <div class="row g-0">
    <div class="col-md-4">
      <% @logo = StockQuote::Stock.logo(@stock.ticker) %>
      <img src="<%= @logo.url %>" class="img-fluid rounded-start"> 
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><%= @ticker.company_name%></h5>
        <% @info = StockQuote::Stock.company(@stock.ticker) %>
        <p class="card-text"> <strong>Descripción:</strong> <%= @info.description %></p>
        <p class="card-text"><small ><strong>Símbolo ticker:</strong> <%= @ticker.symbol %></small></p>
        <p class="card-text"><small ><strong>Precio actual:</strong> $<%= number_with_precision(@ticker.latest_price, :precision =>2, :delimiter => ',') %></small></p>
        <p class="card-text"><small ><strong>Capital:</strong> $<%= number_with_precision(@ticker.market_cap, :precision =>0, :delimiter => ',') %></small></p>
      </div>
    </div>
  </div>
</div>

        
<% end %>

<br/><br/>


<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>